# Datasource


 spring:
  datasource:
    initialize: true
    url: jdbc:mysql://localhost:3306/hipremiumcalc
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

    
 server:
  port: 9999